###
GET http://localhost:9999/results/izanlopez256.3@gmail.com

###
GET http://localhost:9999/languages/all/1

###
GET http://localhost:9999/tests/1

###
GET http://localhost:9999/results/izanlopez256.3@gmail.com/1

###
POST http://localhost:9999/users/login
Content-Type: application/json

{
    "email": "izanlopez256.3@gmail.com",
    "passwd": "ejemplo123#"
}

###
POST http://localhost:9999/users/register
Content-Type: application/json

{
    "email": "izanlopez256@gmail.com",
    "userName": "Macarrones Con Queso",
    "passwd": "patataWarrior"
}

